// This file is auto generated by [`cg`] from [`schema`].
//
// **DO NOT EDIT THIS FILE**,
//
// Edit `cg` or `schema` instead.
//
// [cg]: https://github.com/teloxide/cg
// [`schema`]: https://github.com/WaffleLapkin/tg-methods-schema
use serde::Serialize;

use crate::types::{InlineQueryResult, SentWebAppMessage};

impl_payload! {
    /// Use this method to set the result of an interaction with a [Web App] and send a corresponding message on behalf of the user to the chat from which the query originated.
    ///
    /// [Web App]: https://core.telegram.org/bots/webapps
    #[derive(Debug, PartialEq, Clone, Serialize)]
    pub AnswerWebAppQuery (AnswerWebAppQuerySetters) => SentWebAppMessage {
        required {
            /// Unique identifier for the query to be answered
            pub web_app_query_id: String [into],
            /// A JSON-serialized object describing the message to be sent
            pub result: InlineQueryResult,
        }
    }
}
