// This file is auto generated by [`cg`] from [`schema`].
//
// **DO NOT EDIT THIS FILE**,
//
// Edit `cg` or `schema` instead.
//
// [cg]: https://github.com/teloxide/cg
// [`schema`]: https://github.com/WaffleLapkin/tg-methods-schema
use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to remove webhook integration if you decide to switch back to [`GetUpdates`]. Returns True on success. Requires no parameters.
    ///
    /// [`GetUpdates`]: crate::payloads::GetUpdates
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub DeleteWebhook (DeleteWebhookSetters) => True {

        optional {
            /// Pass _True_ to drop all pending updates
            pub drop_pending_updates: bool,
        }
    }
}
