//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::ChatAdministratorRights;

impl_payload! {
    /// Use this method to get the current value of the bot's menu button in a private chat, or the default menu button.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetMyDefaultAdministratorRights (GetMyDefaultAdministratorRightsSetters) => ChatAdministratorRights {
        optional {
            /// Pass _True_ to get default administrator rights of the bot in channels. Otherwise, default administrator rights of the bot for groups and supergroups will be returned.
            pub for_channels: bool,
        }
    }
}
