// This file is auto generated by `cg` <https://github.com/teloxide/cg> (455146e).
// **DO NOT EDIT THIS FILE**,
// edit `cg` instead.
use serde::Serialize;

use crate::types::WebhookInfo;

impl_payload! {
    /// Use this method to get current webhook status. Requires no parameters. On success, returns a [`WebhookInfo`] object. If the bot is using [`GetUpdates`], will return an object with the _url_ field empty.
    ///
    /// [`GetUpdates`]: crate::payloads::GetUpdates
    /// [`WebhookInfo`]: crate::types::WebhookInfo
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetWebhookInfo (GetWebhookInfoSetters) => WebhookInfo {

    }
}
