// This file is auto generated by [`cg`] from [`schema`].
//
// **DO NOT EDIT THIS FILE**,
//
// Edit `cg` or `schema` instead.
//
// [cg]: https://github.com/teloxide/cg
// [`schema`]: https://github.com/WaffleLapkin/tg-methods-schema
use serde::Serialize;

use crate::types::ChatId;

impl_payload! {
    /// Use this method to get the number of members in a chat. Returns _Int_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetChatMembersCount (GetChatMembersCountSetters) => u32 {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: ChatId [into],
        }
    }
}
