// This file is auto generated by [`cg`] from [`schema`].
//
// **DO NOT EDIT THIS FILE**,
//
// Edit `cg` or `schema` instead.
//
// [cg]: https://github.com/teloxide/cg
// [`schema`]: https://github.com/WaffleLapkin/tg-methods-schema
use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to move a sticker in a set created by the bot to a specific position. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetStickerPositionInSet (SetStickerPositionInSetSetters) => True {
        required {
            /// File identifier of the sticker
            pub sticker: String [into],
            /// New sticker position in the set, zero-based
            pub position: u32,
        }
    }
}
