//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Message, MessageId, Recipient, ReplyMarkup};

impl_payload! {
    /// Use this method to edit live location messages. A location can be edited until its live_period expires or editing is explicitly disabled by a call to [`StopMessageLiveLocation`]. On success, the edited Message is returned.
    ///
    /// See also: [`StopMessageLiveLocationInline`](crate::payloads::StopMessageLiveLocationInline)
    ///
    /// [`Message`]: crate::types::Message
    /// [`StopMessageLiveLocation`]: crate::payloads::StopMessageLiveLocation
    #[derive(Debug, PartialEq, Clone, Serialize)]
    pub StopMessageLiveLocation (StopMessageLiveLocationSetters) => Message {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// Identifier of the message to edit
            #[serde(flatten)]
            pub message_id: MessageId,
            /// Latitude of new location
            pub latitude: f64,
            /// Longitude of new location
            pub longitude: f64,
        }
        optional {
            /// Additional interface options. A JSON-serialized object for an [inline keyboard], [custom reply keyboard], instructions to remove reply keyboard or to force a reply from the user.
            ///
            /// [inline keyboard]: https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating
            /// [custom reply keyboard]: https://core.telegram.org/bots#keyboards
            pub reply_markup: ReplyMarkup [into],
        }
    }
}
