//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InlineQueryResult, SentGuestMessage};

impl_payload! {
    /// Use this method to reply to a received guest message. On success, a [`SentGuestMessage`] object is returned.
    ///
    /// [`SentGuestMessage`]: crate::types::SentGuestMessage
    #[derive(Debug, PartialEq, Clone, Serialize)]
    pub AnswerGuestQuery (AnswerGuestQuerySetters) => SentGuestMessage {
        required {
            /// Unique identifier for the query to be answered
            pub guest_query_id: String [into],
            /// An object describing the message to be sent
            pub result: InlineQueryResult,
        }
    }
}
