//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, OwnedGiftId, True};

impl_payload! {
    /// Converts a given regular gift to Telegram Stars. Requires the _can_convert_gifts_to_stars_ business bot right. Returns _true_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub ConvertGiftToStars (ConvertGiftToStarsSetters) => True {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier of the regular gift that should be converted to Telegram Stars
            pub owned_gift_id: OwnedGiftId,
        }
    }
}
