//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageId, True};

impl_payload! {
    /// Use this method to decline a suggested post in a direct messages chat. The bot must have the 'can_manage_direct_messages' administrator right in the corresponding channel chat. Returns `true` on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeclineSuggestedPost (DeclineSuggestedPostSetters) => True {
        required {
            /// Unique identifier for the target direct messages chat
            pub chat_id: ChatId [into],
            /// Identifier of a suggested post message to decline
            #[serde(flatten)]
            pub message_id: MessageId,
        }
        optional {
            /// Comment for the creator of the suggested post; 0-128 characters
            pub comment: String [into],
        }
    }
}
