//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, Recipient, True, UserId};

impl_payload! {
    /// Use this method to remove up to 10000 recent reactions in a group or a supergroup chat added by a given user or chat. The bot must have the 'can_delete_messages' administrator right in the chat. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteAllMessageReactions (DeleteAllMessageReactionsSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup in the format @username
            pub chat_id: Recipient [into],
        }
        optional {
            /// Identifier of the user whose reactions will be removed, if the reactions were added by a user
            pub user_id: UserId,
            /// Identifier of the chat whose reactions will be removed, if the reactions were added by a chat
            pub actor_chat_id: ChatId [into],
        }
    }
}
