//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageId, Recipient, True, UserId};

impl_payload! {
    /// Use this method to remove a reaction from a message in a group or a supergroup chat. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub DeleteMessageReaction (DeleteMessageReactionSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target supergroup
            pub chat_id: Recipient [into],
            /// Identifier of the target message
            #[serde(flatten)]
            pub message_id: MessageId,
        }
        optional {
            /// Identifier of the user whose reaction will be removed
            pub user_id: UserId,
            /// Identifier of the chat whose reaction will be removed
            pub actor_chat_id: ChatId [into],
        }
    }
}
