//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{CustomEmojiId, Recipient, ThreadId, True};

impl_payload! {
    /// Use this method to edit name and icon of a topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have _can\_manage\_topics_ administrator rights, unless it is the creator of the topic. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditForumTopic (EditForumTopicSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// Unique identifier for the target message thread of the forum topic
            pub message_thread_id: ThreadId,
        }
        optional {
            /// Topic name, 0-128 characters. If not specified or empty, the current name of the topic will be kept
            pub name: String [into],
            /// Unique identifier of the custom emoji shown as the topic icon. Use `getForumTopicIconStickers` to get all allowed custom emoji identifiers. Pass an empty string to remove the icon. If not specified, the current icon will be kept
            pub icon_custom_emoji_id: CustomEmojiId,
        }
    }
}
