//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{TelegramTransactionId, True, UserId};

impl_payload! {
    /// Allows the bot to cancel or re-enable extension of a subscription paid in Telegram Stars. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub EditUserStarSubscription (EditUserStarSubscriptionSetters) => True {
        required {
            /// Identifier of the user whose subscription will be edited
            pub user_id: UserId,
            /// Telegram payment identifier for the subscription
            pub telegram_payment_charge_id: TelegramTransactionId,
            /// Pass `true` to cancel extension of the user subscription; the subscription must be active up to the end of the current subscription period. Pass `false` to allow the user to re-enable a subscription that was previously canceled by the bot.
            pub is_canceled: bool,
        }
    }
}
