//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{Message, UserId};

impl_payload! {
    /// Use this method to get the last messages from the personal chat of a given user. On success, an array of [`Message`] objects is returned.
    ///
    /// [`Message`]: crate::types::Message
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserPersonalChatMessages (GetUserPersonalChatMessagesSetters) => Vec<Message> {
        required {
            /// Unique identifier for the target user
            pub user_id: UserId,
            /// The maximum number of messages to return
            pub limit: u8,
        }
    }
}
