//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::StarAmount;

impl_payload! {
    /// A method to get the current Telegram Stars balance of the bot. Requires no parameters. On success, returns a [`StarAmount`] object.
    ///
    /// [`StarAmount`]: crate::types::StarAmount
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetMyStarBalance (GetMyStarBalanceSetters) => StarAmount {

    }
}
