//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::Me;

impl_payload! {
    /// A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a [`User`] object.
    ///
    /// [`User`]: crate::types::User
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetMe (GetMeSetters) => Me {

    }
}
