//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::UserId;

impl_payload! {
    /// Use this method to get the token of a managed bot. Returns the token as _String_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetManagedBotToken (GetManagedBotTokenSetters) => String {
        required {
            /// User identifier of the managed bot whose token will be returned
            pub user_id: UserId,
        }
    }
}
