//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::Sticker;

impl_payload! {
    /// Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user. Requires no parameters. Returns an Array of `Sticker` objects.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetForumTopicIconStickers (GetForumTopicIconStickersSetters) => Vec<Sticker> {

    }
}
