//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{OwnedGifts, UserId};

impl_payload! {
    /// Returns the gifts owned and hosted by a user. Returns [`OwnedGifts`] on success.
    ///
    /// [`OwnedGifts`]: crate::types::OwnedGifts
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub GetUserGifts (GetUserGiftsSetters) => OwnedGifts {
        required {
            /// Unique identifier of the user
            pub user_id: UserId,
        }
        optional {
            /// Pass True to exclude unlimited gifts
            pub exclude_unlimited: bool,
            /// Pass True to exclude limited upgradable gifts
            pub exclude_limited_upgradable: bool,
            /// Pass True to exclude limited non-upgradable gifts
            pub exclude_limited_non_upgradable: bool,
            /// Pass True to exclude gifts assigned from the TON blockchain
            pub exclude_from_blockchain: bool,
            /// Pass True to exclude unique gifts
            pub exclude_unique: bool,
            /// Pass True to sort results by gift price
            pub sort_by_price: bool,
            /// Offset of the first entry to return
            pub offset: String [into],
            /// The maximum number of gifts to be returned
            pub limit: u8,
        }
    }
}
