//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::StarTransactions;

impl_payload! {
    /// Returns the bot's Telegram Star transactions in chronological order. On success, returns a [`StarTransactions`] object..
    ///
    /// [`StarTransactions`]: crate::types::StarTransactions
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetStarTransactions (GetStarTransactionsSetters) => StarTransactions {
        optional {
            /// Number of transactions to skip in the response
            pub offset: u32,
            /// The maximum number of transactions to be retrieved. Values between 1-100 are accepted. Defaults to 100.
            pub limit: u8,
        }
    }
}
