//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MenuButton};

impl_payload! {
    /// Use this method to get the current value of the bot's menu button in a private chat, or the default menu button.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub GetChatMenuButton (GetChatMenuButtonSetters) => MenuButton {
        optional {
            /// Unique identifier for the target private chat. If not specified, default bot's menu button will be returned
            pub chat_id: ChatId [into],
        }
    }
}
