//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, MessageId, Recipient, True};

impl_payload! {
    /// Use this method to pin a message in a group, a supergroup, or a channel. The bot must be an administrator in the chat for this to work and must have the 'can_pin_messages' admin right in the supergroup or 'can_edit_messages' admin right in the channel. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub PinChatMessage (PinChatMessageSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// Identifier of a message to pin
            #[serde(flatten)]
            pub message_id: MessageId,
        }
        optional {
            /// Pass True, if it is not necessary to send a notification to all chat members about the new pinned message. Notifications are always disabled in channels.
            pub disable_notification: bool,
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
        }
    }
}
