//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, True};

impl_payload! {
    /// Removes the current profile photo of a managed business account. Requires the _can_edit_profile_photo_ business bot right. Returns _true_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RemoveBusinessAccountProfilePhoto (RemoveBusinessAccountProfilePhotoSetters) => True {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
        }
        optional {
            /// Pass _true_ to remove the public photo, which is visible even if the main photo is hidden by the business account's privacy settings. After the main photo is removed, the previous profile photo (if present) becomes the main photo.
            pub is_public: bool,
        }
    }
}
