//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::UserId;

impl_payload! {
    /// Use this method to revoke the current token of a managed bot and generate a new one. Returns the new token as _String_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub ReplaceManagedBotToken (ReplaceManagedBotTokenSetters) => String {
        required {
            /// User identifier of the managed bot whose token will be replaced
            pub user_id: UserId,
        }
    }
}
