//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, ChatId, Seconds, Story, StoryId};

impl_payload! {
    /// Reposts a story on behalf of a business account from another business account. Returns [`Story`] on success.
    ///
    /// [`Story`]: crate::types::Story
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RepostStory (RepostStorySetters) => Story {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier of the chat which posted the story
            pub from_chat_id: ChatId [into],
            /// Unique identifier of the story that should be reposted
            pub from_story_id: StoryId,
            /// Period after which the story is moved to the archive
            pub active_period: Seconds,
        }
        optional {
            /// Pass True to keep the story accessible after it expires
            pub post_to_chat_page: bool,
            /// Pass True if the content of the story must be protected
            pub protect_content: bool,
        }
    }
}
