//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageEntity, ParseMode, True, UserId};

impl_payload! {
    /// Sends a gift to the given user or channel chat. The gift can't be converted to Telegram Stars by the receiver. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendGift (SendGiftSetters) => True {
        required {
            /// Identifier of the gift
            pub gift_id: String [into],
        }
        optional {
            /// Required if chat_id is not specified. Unique identifier of the target user who will receive the gift.
            pub user_id: UserId,
            /// Required if user_id is not specified. Unique identifier for the chat or username of the channel (in the format @channelusername) that will receive the gift.
            pub chat_id: ChatId [into],
            /// Pass True to pay for the gift upgrade from the bot's balance, thereby making the upgrade free for the receiver
            pub pay_for_upgrade: bool,
            /// Text that will be shown along with the gift; 0–128 characters
            pub text: String [into],
            /// Mode for parsing entities in the text. See formatting options for more details. Entities other than “bold”, “italic”, “underline”, “strikethrough”, “spoiler”, and “custom_emoji” are ignored.
            ///
            /// [formatting options]: https://core.telegram.org/bots/api#formatting-options
            pub text_parse_mode: ParseMode,
            /// A JSON-serialized list of special entities that appear in the gift text. It can be specified instead of text_parse_mode. Entities other than “bold”, “italic”, “underline”, “strikethrough”, “spoiler”, and “custom_emoji” are ignored.
            pub text_entities: Vec<MessageEntity> [collect],
        }
    }
}
