//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{GiftId, MessageEntity, ParseMode, Recipient, True};

impl_payload! {
    /// Sends a gift to the given channel chat. The gift can't be converted to Telegram Stars by the receiver. Returns True on success.
    ///
    /// See also: [`SendGift`](crate::payloads::SendGift)
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendGiftChat (SendGiftChatSetters) => True {
        required {
            /// Unique identifier for the chat or username of the channel that will receive the gift
            pub chat_id: Recipient [into],
            /// Identifier of the gift
            pub gift_id: GiftId,
        }
        optional {
            /// Text that will be shown along with the gift; 0-255 characters
            pub text: String [into],
            /// Mode for parsing entities in the text. See [formatting options] for more details. Entities other than “bold”, “italic”, “underline”, “strikethrough”, “spoiler”, and “custom_emoji” are ignored
            ///
            /// [formatting options]: https://core.telegram.org/bots/api#formatting-options
            pub text_parse_mode: ParseMode,
            /// List of special entities that appear in the gift text. It can be specified instead of text_parse_mode. Entities other than “bold”, “italic”, “underline”, “strikethrough”, “spoiler”, and “custom_emoji” are ignored.
            pub text_entities: Vec<MessageEntity> [collect],
        }
    }
}
