//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{
    BusinessConnectionId, EffectId, InputFile, Message, MessageEntity, ParseMode, Recipient,
    ReplyMarkup, ReplyParameters, SuggestedPostParameters, ThreadId, TopicId,
};

impl_payload! {
    @[multipart = live_photo, photo]
    /// Use this method to send live photos. On success, the sent [`Message`] is returned.
    ///
    /// [`Message`]: crate::types::Message
    #[derive(Debug, Clone, Serialize)]
    pub SendLivePhoto (SendLivePhotoSetters) => Message {
        required {
            /// Unique identifier for the target chat or username of the target channel
            pub chat_id: Recipient [into],
            /// Live photo video to send
            pub live_photo: InputFile,
            /// The static photo to send
            pub photo: InputFile,
        }
        optional {
            /// Unique identifier of the business connection on behalf of which the message will be sent
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Identifier of the direct messages topic to which the message will be sent
            pub direct_messages_topic_id: TopicId,
            /// Live photo caption
            pub caption: String [into],
            /// Mode for parsing entities in the caption
            pub parse_mode: ParseMode,
            /// List of special entities that appear in the caption
            pub caption_entities: Vec<MessageEntity> [collect],
            /// Pass True, if the caption must be shown above the message media
            pub show_caption_above_media: bool,
            /// Pass True if the live photo needs to be covered with a spoiler animation
            pub has_spoiler: bool,
            /// Sends the message silently
            pub disable_notification: bool,
            /// Protects the contents of the sent message from forwarding and saving
            pub protect_content: bool,
            /// Pass True to allow up to 1000 messages per second
            pub allow_paid_broadcast: bool,
            /// Unique identifier of the message effect to be added to the message
            pub message_effect_id: EffectId,
            /// Parameters of the suggested post to send
            pub suggested_post_parameters: SuggestedPostParameters,
            /// Description of the message to reply to
            pub reply_parameters: ReplyParameters,
            /// Additional interface options
            pub reply_markup: ReplyMarkup [into],
        }
    }
}
