//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{True, UserId};

impl_payload! {
    /// Changes the emoji status for a given user that previously allowed the bot to manage their emoji status via the Mini App method requestEmojiStatusAccess. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetUserEmojiStatus (SetUserEmojiStatusSetters) => True {
        required {
            /// Unique identifier of the target user
            pub user_id: UserId,
        }
        optional {
            /// Custom emoji identifier of the emoji status to set. Pass an empty string to remove the status.
            pub emoji_status_custom_emoji_id: String [into],
            /// Expiration date of the emoji status, if any
            pub emoji_status_expiration_date: i64,
        }
    }
}
