//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{True, UserId};

impl_payload! {
    /// Use this method to change the access settings of a managed bot. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetManagedBotAccessSettings (SetManagedBotAccessSettingsSetters) => True {
        required {
            /// User identifier of the managed bot whose access settings will be changed
            pub user_id: UserId,
            /// Pass True if only selected users can access the bot
            pub is_access_restricted: bool,
        }
        optional {
            /// List of up to 10 identifiers of users who will have access to the bot
            pub added_user_ids: Vec<UserId> [collect],
        }
    }
}
