//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MenuButton, True};

impl_payload! {
    /// Use this method to change the bot's menu button in a private chat, or the default menu button.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub SetChatMenuButton (SetChatMenuButtonSetters) => True {
        optional {
            /// Unique identifier for the target private chat. If not specified, default bot's menu button will be changed.
            pub chat_id: ChatId [into],
            /// An object for the new bot's menu button. Defaults to MenuButtonDefault
            pub menu_button: MenuButton,
        }
    }
}
