//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to set the title of a created sticker set. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetStickerSetTitle (SetStickerSetTitleSetters) => True {
        required {
            /// Sticker set name
            pub name: String [into],
            /// Sticker set title, 1-64 characters
            pub title: String [into],
        }
    }
}
