//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{InputFile, Recipient, True};

impl_payload! {
    @[multipart = photo]
    /// Use this method to set a new profile photo for the chat. Photos can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns _True_ on success.
    #[derive(Debug, Clone, Serialize)]
    pub SetChatPhoto (SetChatPhotoSetters) => True {
        required {
            /// Unique identifier for the target chat or username of the target channel (in the format `@channelusername`)
            pub chat_id: Recipient [into],
            /// New chat photo, uploaded using multipart/form-data
            pub photo: InputFile,
        }
    }
}
