//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Use this method to change the list of emoji assigned to a regular or custom emoji sticker. The sticker must belong to a sticker set created by the bot. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SetStickerEmojiList (SetStickerEmojiListSetters) => True {
        required {
            /// File identifier of the sticker
            pub sticker: String [into],
            /// A JSON-serialized list of 1-20 emoji associated with the sticker
            pub emoji_list: Vec<String> [collect],
        }
    }
}
