//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{FileMeta, InputFile, StickerFormat, UserId};

impl_payload! {
    @[multipart = sticker]
    /// Use this method to upload a .PNG file with a sticker for later use in _createNewStickerSet_ and _addStickerToSet_ methods (can be used multiple times). Returns the uploaded File on success.
    #[derive(Debug, Clone, Serialize)]
    pub UploadStickerFile (UploadStickerFileSetters) => FileMeta {
        required {
            /// User identifier of sticker file owner
            pub user_id: UserId,
            /// A file with the sticker in .WEBP, .PNG, .TGS, or .WEBM format. See https://core.telegram.org/stickers for technical requirements. [More info on Sending Files »]
            ///
            /// [More info on Sending Files »]: crate::types::InputFile
            pub sticker: InputFile,
            /// Format of the sticker, must be one of “static”, “animated”, “video”
            pub sticker_format: StickerFormat,
        }
    }
}
